theme: minima
title: Demo datascience portfolio
author: Woody
description: |
  An example of a data science portfolio showcasing coursework and 
  projects. Designed to highlight coding skills, data analysis, and 
  project-based learning.
